name: Generate IPTV XML

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 3 */3 * * *
  push:
    branches:
      - main  # 在 push 到 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4  # 更新到 v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run IPTV XML Generator
      run: |
        python generate_iptv_xml.py

    - name: Move Output to emby folder
      run: |
        mkdir -p ./emby
        rm -f ./emby/MediaBrowser.Channels.IPTV.xml
        mv MediaBrowser.Channels.IPTV.xml ./emby/

    - name: Commit and Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ./emby/MediaBrowser.Channels.IPTV.xml
        git diff --cached --quiet || git commit -m "Add generated IPTV XML file"
        git push
